version: '2'
services:
  web:
    build: .
    command: yarn start
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://bradesco@postgres/bradesco
  postgres:
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bradesco
      POSTGRES_DB: bradesco