### Cadastro de produtos
POST http://localhost:8080/produtos
Content-Type: application/json

{
    "name": "Borracha 2",
    "description": "Boa para apagar desenhos a lápis",
    "type": "tools",
    "count": 5
}

### Pesquisar no elasticsearch produtos
GET http://localhost:8080/produtos/pesquisar/borra

### Mostrar todos os produtos
GET http://localhost:8080/produtos

### Mostrar produto por id
GET http://localhost:8080/produtos/1

### Atualizar o produto
PUT http://localhost:8080/produtos/1
Content-Type: application/json

{
    "name": "Borracha",
    "description": "Boa para apagar desenhos a lápis",
    "type": "tools",
    "count": 5
}

### Atualizar campos do produto
PATCH  http://localhost:8080/produtos/1
Content-Type: application/json

{
    "count": 12
}

### Apagar produto
DELETE http://localhost:8080/produtos/1
