### Cadastro de usuario
POST http://localhost:8080/cadastro
Content-Type: application/json

{
    "name": "Jose",
    "last_name": "Maiko"
}

### Cadastro de produtos
POST http://localhost:8080/cadastro/produto
Content-Type: application/json

{
    "nome": "Caneta",
    "tipo": "utilitary",
    "quantidade": 15,
    "descricao": "Uso geral, escrita, desenho e afins"
}