### Cadastro de usuarios
POST http://localhost:8080/usuario
Content-Type: application/json

{
    "name": "Jhon Mart",
    "email": "jonatas.araripe2@mail.com",
    "gender": "male",
    "birthday": "1998-04-08",
    "password": "a2N23_*2@nc!2021"
}

### Pesquisar no elasticsearch produtos
GET http://localhost:8080/usuario/pesquisar/jho

### Entrar
POST http://localhost:8080/usuario/entrar
Content-Type: application/json

{
    "email": "jonatas.araripe@mail.com",
    "password": "a2N23_*2@nc!2021"
}

### Mostrar todos os usuarios
GET http://localhost:8080/usuario

### Mostrar usuario por id
GET http://localhost:8080/usuario/75b68de2-575a-4c45-aaf1-880fd8e4b757

### Atualizar o usuario
PUT http://localhost:8080/usuario/75b68de2-575a-4c45-aaf1-880fd8e4b757
Content-Type: application/json

{
    "name": "Jonatas Martins",
    "email": "jonatas.martins@mail.com",
    "gender": "male",
    "birthday": "1998-04-08",
    "password": "a2N23_*2@nc!2021"
}

### Atualizar campos do usuario
PATCH  http://localhost:8080/usuario/75b68de2-575a-4c45-aaf1-880fd8e4b757
Content-Type: application/json

{
    "password": "a2K23_*2@nc!2021"
}

### Apagar usuario
DELETE http://localhost:8080/usuario/75b68de2-575a-4c45-aaf1-880fd8e4b757
