name: Deploy project

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install

      - name: Run migrations 
        run: yarn migrate

      - name: Run seeds 
        run: yarn seed

      - name: Run unitary test 
        run: yarn test
      
      - name: Config test
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: coverage
          retention-days: 3

      - name: Generation badges
        run: yarn ge:badges

      - name: Deploy badges
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            badges/*.svg
          commit-msg: deploy system
          github-token: ${{ secrets.GITHUB_TOKEN }}